[pytest]
testpaths = tests py
pythonpath = py py/acquire/bundesanzeiger
<<<<<<< Updated upstream
norecursedirs = .venv node_modules ui
=======
norecursedirs = .venv node_modules ui
>>>>>>> Stashed changes
